import { leagueConfig } from "@/lib/league-config";
import type {
  Championship,
  Driver,
  NewsPost,
  Race,
  RaceResult,
  Standing,
  StewardReport,
  Team,
} from "@/types/league";

export const championships: Championship[] = [
  {
    id: "mel-multiclass-2026",
    name: "MEL European Endurance Cup",
    carClass: "Multi-class",
    description:
      "A class-based Le Mans Ultimate championship for European and global sim racing drivers.",
    status: "active",
  },
];

export const teams: Team[] = [
  {
    id: "apex-vector-racing",
    name: "Apex Vector Racing",
    logoUrl: "/teams/apex-vector-racing.svg",
    country: "Germany",
    description: "A disciplined endurance squad built around clean stints and efficient strategy.",
  },
  {
    id: "silverline-motorsport",
    name: "Silverline Motorsport",
    logoUrl: "/teams/silverline-motorsport.svg",
    country: "France",
    description: "A balanced driver development team with a focus on consistency and race craft.",
  },
  {
    id: "velocity-works",
    name: "Velocity Works",
    logoUrl: "/teams/velocity-works.svg",
    country: "Italy",
    description: "An LMGT3-focused team with strong qualifying pace and clean traffic management.",
  },
  {
    id: "carbon-edge-racing",
    name: "Carbon Edge Racing",
    logoUrl: "/teams/carbon-edge-racing.svg",
    country: "Netherlands",
    description: "A multi-class roster built for broadcast-ready endurance racing.",
  },
];

export const drivers: Driver[] = [
  {
    id: "alex-martin",
    displayName: "Alex Martin",
    country: "France",
    region: "Paris",
    carNumber: 7,
    teamId: "apex-vector-racing",
    discordUsername: "alexmartin",
    steamId: "76561198000000007",
    preferredClass: "Hypercar",
    preferredCar: "Hypercar class entry",
    rating: 1842,
    safetyRating: "A",
    approvalStatus: "approved",
  },
  {
    id: "lucas-weber",
    displayName: "Lucas Weber",
    country: "Germany",
    region: "Munich",
    carNumber: 34,
    teamId: "apex-vector-racing",
    discordUsername: "lucasweber",
    steamId: "76561198000000034",
    preferredClass: "LMP2",
    preferredCar: "LMP2 class entry",
    rating: 1715,
    safetyRating: "A",
    approvalStatus: "approved",
  },
  {
    id: "daniel-rossi",
    displayName: "Daniel Rossi",
    country: "Italy",
    region: "Milan",
    carNumber: 11,
    teamId: "silverline-motorsport",
    discordUsername: "danielrossi",
    steamId: "76561198000000011",
    preferredClass: "LMGT3",
    preferredCar: "LMGT3 class entry",
    rating: 1688,
    safetyRating: "B",
    approvalStatus: "approved",
  },
  {
    id: "thomas-reed",
    displayName: "Thomas Reed",
    country: "United Kingdom",
    region: "Manchester",
    carNumber: 22,
    teamId: "velocity-works",
    discordUsername: "thomasreed",
    steamId: "76561198000000022",
    preferredClass: "LMGT3",
    preferredCar: "LMGT3 class entry",
    rating: 1901,
    safetyRating: "S",
    approvalStatus: "approved",
  },
  {
    id: "max-keller",
    displayName: "Max Keller",
    country: "Austria",
    region: "Vienna",
    carNumber: 95,
    teamId: "carbon-edge-racing",
    discordUsername: "maxkeller",
    steamId: "76561198000000095",
    preferredClass: "Hypercar",
    preferredCar: "Hypercar class entry",
    rating: 1770,
    safetyRating: "A",
    approvalStatus: "approved",
  },
  {
    id: "sofia-janssen",
    displayName: "Sofia Janssen",
    country: "Netherlands",
    region: "Rotterdam",
    carNumber: 61,
    teamId: "carbon-edge-racing",
    discordUsername: "sofiajanssen",
    steamId: "76561198000000061",
    preferredClass: "LMP2",
    preferredCar: "LMP2 class entry",
    rating: 1644,
    safetyRating: "B",
    approvalStatus: "pending",
  },
];

export const races: Race[] = [
  {
    id: "round-1-spa-francorchamps",
    championshipId: "mel-multiclass-2026",
    name: "June 12 - Spa-Francorchamps",
    trackName: "Circuit de Spa-Francorchamps",
    raceDate: "2026-06-12T21:00:00+03:00",
    format: "20m Qualifying + 40m Sprint Race",
    category: "Sprint Race",
    setup: "Fixed setup",
    carClass: "Multi-class",
    registrationStatus: "open",
    status: "upcoming",
    streamUrl: leagueConfig.twitchUrl,
  },
  {
    id: "round-2-monza",
    championshipId: "mel-multiclass-2026",
    name: "June 19 - Monza",
    trackName: "Autodromo Nazionale Monza",
    raceDate: "2026-06-19T21:00:00+03:00",
    format: "20m Qualifying + 40m Sprint Race",
    category: "Sprint Race",
    setup: "Fixed setup",
    carClass: "Multi-class",
    registrationStatus: "open",
    status: "upcoming",
    streamUrl: leagueConfig.twitchUrl,
  },
  {
    id: "round-3-fuji",
    championshipId: "mel-multiclass-2026",
    name: "June 26 - Fuji Speedway",
    trackName: "Fuji Speedway",
    raceDate: "2026-06-26T21:00:00+03:00",
    format: "20m Qualifying + 40m Sprint Race",
    category: "Sprint Race",
    setup: "Fixed setup",
    carClass: "Multi-class",
    registrationStatus: "open",
    status: "upcoming",
    streamUrl: leagueConfig.twitchUrl,
  },
  {
    id: "round-4-le-mans",
    championshipId: "mel-multiclass-2026",
    name: "July 3 - Le Mans",
    trackName: "Circuit de la Sarthe",
    raceDate: "2026-07-03T21:00:00+03:00",
    format: "20m Qualifying + 40m Sprint Race",
    category: "Sprint Race",
    setup: "Fixed setup",
    carClass: "Multi-class",
    registrationStatus: "open",
    status: "upcoming",
    streamUrl: leagueConfig.twitchUrl,
  },
  {
    id: "preseason-portimao",
    championshipId: "mel-multiclass-2026",
    name: "Preseason Test - Portimao",
    trackName: "Algarve International Circuit",
    raceDate: "2026-05-03T18:00:00+02:00",
    format: "Practice + Qualifying + Test Race",
    category: "Test Race",
    setup: "Fixed setup",
    carClass: "LMGT3",
    registrationStatus: "closed",
    status: "completed",
    streamUrl: leagueConfig.twitchUrl,
    replayUrl: "https://www.youtube.com/@medenduranceleague",
  },
];

export const raceResults: RaceResult[] = [
  {
    id: "pre-1",
    raceId: "preseason-portimao",
    driverId: "thomas-reed",
    teamId: "velocity-works",
    position: 1,
    qualifyingPosition: 2,
    points: 26,
    bestLap: "1:42.381",
    totalTime: "45:14.920",
    gap: "Leader",
    lapsCompleted: 26,
    penaltiesSeconds: 0,
    penaltyPoints: 0,
    dnf: false,
    dns: false,
    dsq: false,
    fastestLap: true,
  },
  {
    id: "pre-2",
    raceId: "preseason-portimao",
    driverId: "alex-martin",
    teamId: "apex-vector-racing",
    position: 2,
    qualifyingPosition: 1,
    points: 18,
    bestLap: "1:42.644",
    totalTime: "45:18.301",
    gap: "+3.381",
    lapsCompleted: 26,
    penaltiesSeconds: 0,
    penaltyPoints: 0,
    dnf: false,
    dns: false,
    dsq: false,
    fastestLap: false,
  },
  {
    id: "pre-3",
    raceId: "preseason-portimao",
    driverId: "max-keller",
    teamId: "carbon-edge-racing",
    position: 3,
    qualifyingPosition: 4,
    points: 15,
    bestLap: "1:43.008",
    totalTime: "45:25.871",
    gap: "+10.951",
    lapsCompleted: 26,
    penaltiesSeconds: 5,
    penaltyPoints: 1,
    dnf: false,
    dns: false,
    dsq: false,
    fastestLap: false,
  },
  {
    id: "pre-4",
    raceId: "preseason-portimao",
    driverId: "daniel-rossi",
    teamId: "silverline-motorsport",
    position: 4,
    qualifyingPosition: 3,
    points: 12,
    bestLap: "1:43.190",
    totalTime: "45:30.617",
    gap: "+15.697",
    lapsCompleted: 26,
    penaltiesSeconds: 0,
    penaltyPoints: 0,
    dnf: false,
    dns: false,
    dsq: false,
    fastestLap: false,
  },
];

export const driverStandings: Standing[] = raceResults
  .map((result) => ({
    id: `standing-${result.driverId}`,
    championshipId: "mel-multiclass-2026",
    driverId: result.driverId,
    totalPoints: result.points,
    wins: result.position === 1 ? 1 : 0,
    podiums: result.position <= 3 ? 1 : 0,
    fastestLaps: result.fastestLap ? 1 : 0,
    racesStarted: result.dns ? 0 : 1,
    dnfCount: result.dnf ? 1 : 0,
    penaltyPoints: result.penaltyPoints,
    position: result.position,
  }))
  .sort((a, b) => b.totalPoints - a.totalPoints)
  .map((standing, index) => ({ ...standing, position: index + 1 }));

export const teamStandings: Standing[] = teams
  .map((team) => {
    const teamResults = raceResults.filter((result) => result.teamId === team.id);
    return {
      id: `team-standing-${team.id}`,
      championshipId: "mel-multiclass-2026",
      teamId: team.id,
      totalPoints: teamResults.reduce((sum, result) => sum + result.points, 0),
      wins: teamResults.filter((result) => result.position === 1).length,
      podiums: teamResults.filter((result) => result.position <= 3).length,
      fastestLaps: teamResults.filter((result) => result.fastestLap).length,
      racesStarted: teamResults.filter((result) => !result.dns).length,
      dnfCount: teamResults.filter((result) => result.dnf).length,
      penaltyPoints: teamResults.reduce((sum, result) => sum + result.penaltyPoints, 0),
      position: 0,
    };
  })
  .sort((a, b) => b.totalPoints - a.totalPoints)
  .map((standing, index) => ({ ...standing, position: index + 1 }));

export const stewardReports: StewardReport[] = [
  {
    id: "sr-001",
    raceId: "preseason-portimao",
    reportingDriverId: "daniel-rossi",
    reportedDriverId: "max-keller",
    lapNumber: 14,
    description: "Side contact at T5 after overlap was established on corner entry.",
    evidenceUrl: "https://youtu.be/example?t=812",
    status: "accepted",
    stewardDecision: "5s time penalty and 1 penalty point for avoidable contact.",
  },
  {
    id: "sr-002",
    raceId: "preseason-portimao",
    reportingDriverId: "alex-martin",
    reportedDriverId: "thomas-reed",
    lapNumber: 4,
    description: "Track limits review requested for consecutive exits at the final corner.",
    evidenceUrl: "https://youtu.be/example?t=240",
    status: "rejected",
    stewardDecision: "No further action. Driver remained within allowed limits.",
  },
];

export const newsPosts: NewsPost[] = [
  {
    id: "news-1",
    title: "Driver applications open for the first MEL endurance season",
    body: "Applications are reviewed manually to keep the grid clean, respectful and broadcast-ready.",
    published: true,
    createdAt: "2026-05-07T09:00:00+02:00",
  },
  {
    id: "news-2",
    title: "Preseason test complete at Portimao",
    body: "Race control validated the result import workflow and steward reporting process after the first community test.",
    published: true,
    createdAt: "2026-05-04T21:00:00+02:00",
  },
];

export const getTeam = (teamId?: string) => teams.find((team) => team.id === teamId);
export const getDriver = (driverId?: string) => drivers.find((driver) => driver.id === driverId);
export const getRace = (raceId?: string) => races.find((race) => race.id === raceId);

export const nextRace =
  races
    .filter((race) => race.status !== "completed")
    .sort((a, b) => new Date(a.raceDate).getTime() - new Date(b.raceDate).getTime())[0] ?? races[0];
